-- MySQL Script generated by MySQL Workbench
-- Tue Oct 30 20:42:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema iweb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iweb` ;

-- -----------------------------------------------------
-- Schema iweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iweb` ;
USE `iweb` ;

-- -----------------------------------------------------
-- Table `iweb`.`Serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iweb`.`Serie` ;

CREATE TABLE IF NOT EXISTS `iweb`.`Serie` (
  `idSerie` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  `valoracion` INT NULL,
  PRIMARY KEY (`idSerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iweb`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `iweb`.`Entrega` (
  `id` VARCHAR(45) NOT NULL,
  `anotacion` VARCHAR(150) NULL,
  `Fecha de entrega` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb`.`Serie_has_Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iweb`.`Serie_has_Entrega` ;

CREATE TABLE IF NOT EXISTS `iweb`.`Serie_has_Entrega` (
  `Serie_idSerie` INT NOT NULL,
  `Entrega_id` VARCHAR(45) NULL,
  PRIMARY KEY (`Serie_idSerie`),
  INDEX `fk_Serie_has_Entrega_Entrega1_idx` (`Entrega_id` ASC),
  INDEX `fk_Serie_has_Entrega_Serie_idx` (`Serie_idSerie` ASC),
  UNIQUE INDEX `Entrega_id_UNIQUE` (`Entrega_id` ASC),
  CONSTRAINT `fk_Serie_has_Entrega_Serie`
    FOREIGN KEY (`Serie_idSerie`)
    REFERENCES `iweb`.`Serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serie_has_Entrega_Entrega1`
    FOREIGN KEY (`Entrega_id`)
    REFERENCES `iweb`.`Entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
